spring.cloud.config.server.git.uri=https://github.com/venkatesh807275/configserver
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8888
